export const siteConfig = {
  name: "PureTalks",
  tagline: "Private Online Consultations & Mental Clarity Sanctuary",
  description:
    "100% confidential, private online consultations with licensed psychologists, relationship counselors, and executive coaches. A safe sanctuary with anonymous mode and zero data logging.",
  url: "https://puretalks.in",
  ogImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1200&q=80",
  contact: {
    email: "care@puretalks.in",
    supportEmail: "support@puretalks.in",
    whatsapp: "+91 98400 12345",
    address: "PureTalks Mental Health & Wellness Sanctuary, India",
  },
  links: {
    twitter: "https://twitter.com/puretalks_in",
    instagram: "https://instagram.com/puretalks.in",
    linkedin: "https://linkedin.com/company/puretalks",
  },
  keywords: [
    "private online consultation",
    "confidential therapy",
    "licensed psychologists",
    "anonymous mental health counseling",
    "marriage counseling",
    "career coaching",
    "stress relief guidance",
    "mental wellness sanctuary",
    "online therapy India",
    "confidential counseling online",
    "anonymous psychologist online",
    "best online mental health platform",
    "marriage counselor India",
    "relationship counseling online",
    "executive coaching India",
    "mindfulness sessions online",
    "youth mentoring India",
    "private video consultation",
    "confidential marriage guidance",
    "online therapy for anxiety",
    "online therapy for depression",
    "stress management online",
    "personal development coaching",
    "mental health support India",
    "affordable online therapy",
  ],
  phone: "+919840012345",
  priceRange: "₹399 - ₹1999",
};
